set_property SRC_FILE_INFO {cfile:C:/Users/mloui/Documents/ROIC/pwm/pwm.srcs/constrs_1/new/pwmpins.xdc rfile:../../../pwm.srcs/constrs_1/new/pwmpins.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP8 [get_ports pwm_out]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE10 [get_ports rst]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K20 [get_ports clk]
