webtalk_init -webtalk_dir C:\\Users\\mloui\\Documents\\ROIC\\roic_test\\roic_test.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-07-24 15:24:17" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211222071_1777533371_210679059_361" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "vradf8il960hsr12lt94o7tunj" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.061 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1532460191278" -context "sdk\\\\hardware/1532460191278"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1532460191278"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1532460191278"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1532460191278"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4" -context "sdk\\\\hardware/1532460191278"
webtalk_add_data -client sdk -key Arch -value "kintexu" -context "sdk\\\\hardware/1532460191278"
webtalk_add_data -client sdk -key Device -value "xcku040" -context "sdk\\\\hardware/1532460191278"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1532460191278"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1532460191278"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1532460191278"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1532460191278"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1532460257124"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1532460257124"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1532460257124"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1532460257124"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1532460257124"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1532460257124"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1532460257124"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1532460257124"
webtalk_transmit -clientid 2282918233 -regid "211222071_1777533371_210679059_361" -xml C:\\Users\\mloui\\Documents\\ROIC\\roic_test\\roic_test.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\mloui\\Documents\\ROIC\\roic_test\\roic_test.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\mloui\\Documents\\ROIC\\roic_test\\roic_test.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
