# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/contrs_roic.xdc

# Block Designs: bd/base_mb/base_mb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb || ORIG_REF_NAME==base_mb} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_microblaze_0_0/base_mb_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_microblaze_0_0 || ORIG_REF_NAME==base_mb_microblaze_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_mdm_1_0/base_mb_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_mdm_1_0 || ORIG_REF_NAME==base_mb_mdm_1_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_clk_wiz_1_0/base_mb_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_clk_wiz_1_0 || ORIG_REF_NAME==base_mb_clk_wiz_1_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_rst_clk_wiz_1_100M_0/base_mb_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==base_mb_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_uartlite_0_0/base_mb_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_uartlite_0_0 || ORIG_REF_NAME==base_mb_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_microblaze_0_axi_periph_0/base_mb_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_microblaze_0_axi_periph_0 || ORIG_REF_NAME==base_mb_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xbar_0/base_mb_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xbar_0 || ORIG_REF_NAME==base_mb_xbar_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_dlmb_v10_0/base_mb_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_dlmb_v10_0 || ORIG_REF_NAME==base_mb_dlmb_v10_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_ilmb_v10_0/base_mb_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_ilmb_v10_0 || ORIG_REF_NAME==base_mb_ilmb_v10_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_dlmb_bram_if_cntlr_0/base_mb_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==base_mb_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_ilmb_bram_if_cntlr_0/base_mb_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==base_mb_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_lmb_bram_0/base_mb_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_lmb_bram_0 || ORIG_REF_NAME==base_mb_lmb_bram_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_pwmcore_0_0/base_mb_pwmcore_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_pwmcore_0_0 || ORIG_REF_NAME==base_mb_pwmcore_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_roic_interface_driver_0_0/base_mb_roic_interface_driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_roic_interface_driver_0_0 || ORIG_REF_NAME==base_mb_roic_interface_driver_0_0} -quiet] -quiet

# XDC: bd/base_mb/base_mb_ooc.xdc
